package Interfaz;

import Automatas.Tabla_AFD_AFND;
import Diccionario.EscaneoDiccionario;
import Diccionario.Diccionario;
import Analizador.Interfaz;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author juani
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * InterfazDiccionario
     */
    public Menu_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Interfaz");
        this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icon app.png"))); //icono de la app
        EscaneoDiccionario p1 = new EscaneoDiccionario();
        CambioPanel(p1);
    }

    private void CambioPanel(JPanel p) {
        p.setSize(890, 540);
        p.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    private void CambioJframe(JFrame j) {
        j.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        barraOpciones = new javax.swing.JPanel();
        btnAnalizador = new javax.swing.JButton();
        btnEscaneo = new javax.swing.JButton();
        btnDiccionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAFDoAFND = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setPreferredSize(new java.awt.Dimension(780, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        background.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 900, 600));

        barraOpciones.setBackground(new java.awt.Color(98, 150, 185));
        barraOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnalizador.setBackground(new java.awt.Color(98, 150, 185));
        btnAnalizador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon Analizador.png"))); // NOI18N
        btnAnalizador.setText("Analizador");
        btnAnalizador.setBorder(null);
        btnAnalizador.setBorderPainted(false);
        btnAnalizador.setContentAreaFilled(false);
        btnAnalizador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnalizador.setFocusable(false);
        btnAnalizador.setIconTextGap(10);
        btnAnalizador.setOpaque(true);
        btnAnalizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnalizadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalizadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalizadorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnalizadorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAnalizadorMouseReleased(evt);
            }
        });
        btnAnalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizadorActionPerformed(evt);
            }
        });
        barraOpciones.add(btnAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        btnEscaneo.setBackground(new java.awt.Color(98, 150, 185));
        btnEscaneo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEscaneo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon Escanear.png"))); // NOI18N
        btnEscaneo.setText("Escaneo");
        btnEscaneo.setToolTipText("");
        btnEscaneo.setBorder(null);
        btnEscaneo.setBorderPainted(false);
        btnEscaneo.setContentAreaFilled(false);
        btnEscaneo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscaneo.setFocusable(false);
        btnEscaneo.setIconTextGap(10);
        btnEscaneo.setName(""); // NOI18N
        btnEscaneo.setOpaque(true);
        btnEscaneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscaneoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEscaneoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEscaneoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEscaneoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEscaneoMouseReleased(evt);
            }
        });
        btnEscaneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscaneoActionPerformed(evt);
            }
        });
        barraOpciones.add(btnEscaneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 50));

        btnDiccionario.setBackground(new java.awt.Color(98, 150, 185));
        btnDiccionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDiccionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon Diccionario.png"))); // NOI18N
        btnDiccionario.setText("Diccionario");
        btnDiccionario.setBorder(null);
        btnDiccionario.setBorderPainted(false);
        btnDiccionario.setContentAreaFilled(false);
        btnDiccionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiccionario.setFocusable(false);
        btnDiccionario.setIconTextGap(10);
        btnDiccionario.setOpaque(true);
        btnDiccionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiccionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiccionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiccionarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDiccionarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDiccionarioMouseReleased(evt);
            }
        });
        btnDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiccionarioActionPerformed(evt);
            }
        });
        barraOpciones.add(btnDiccionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 50));

        jLabel1.setBackground(new java.awt.Color(46, 123, 216));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APPS");
        barraOpciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btnAFDoAFND.setBackground(new java.awt.Color(98, 150, 185));
        btnAFDoAFND.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAFDoAFND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon AFD.png"))); // NOI18N
        btnAFDoAFND.setText("AFD/AFND");
        btnAFDoAFND.setBorder(null);
        btnAFDoAFND.setBorderPainted(false);
        btnAFDoAFND.setContentAreaFilled(false);
        btnAFDoAFND.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAFDoAFND.setFocusable(false);
        btnAFDoAFND.setIconTextGap(10);
        btnAFDoAFND.setOpaque(true);
        btnAFDoAFND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAFDoAFNDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAFDoAFNDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAFDoAFNDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAFDoAFNDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAFDoAFNDMouseReleased(evt);
            }
        });
        btnAFDoAFND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAFDoAFNDActionPerformed(evt);
            }
        });
        barraOpciones.add(btnAFDoAFND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 150, 50));

        background.add(barraOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*MouseEntered(cuando el mouse se posiciona encima del objeto)
      MouseExited(cuando el mouse sale del objeto)
      MousePressed(cuando el mouse presiona el objeto)
      Mouse Released(cuando el mouse termina la accion de presionar)
      Mouse Clicked(no es igual al presed, espera que se presione y se suelte el click para hacer el evento)
      Mouse Dragged(cuando se arrastra el mouse estando presiondo)*/
    private void btnAnalizadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizadorMouseEntered
        btnAnalizador.setBackground(new Color(171, 197, 215)); //hover
    }//GEN-LAST:event_btnAnalizadorMouseEntered

    private void btnAnalizadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizadorMouseExited
        btnAnalizador.setBackground(new Color(98, 150, 185)); //color de fondo
    }//GEN-LAST:event_btnAnalizadorMouseExited

    private void btnAnalizadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizadorMousePressed
        btnAnalizador.setBackground(new Color(98, 150, 185));

    }//GEN-LAST:event_btnAnalizadorMousePressed

    private void btnAnalizadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizadorMouseReleased

    }//GEN-LAST:event_btnAnalizadorMouseReleased

    private void btnAnalizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizadorMouseClicked
        btnAnalizador.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnAnalizadorMouseClicked

    private void btnAnalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizadorActionPerformed
        Interfaz j1 = new Interfaz();
        CambioJframe(j1);
    }//GEN-LAST:event_btnAnalizadorActionPerformed

    private void btnEscaneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscaneoMouseClicked
        btnEscaneo.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnEscaneoMouseClicked

    private void btnEscaneoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscaneoMouseEntered
        btnEscaneo.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnEscaneoMouseEntered

    private void btnEscaneoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscaneoMouseExited
        btnEscaneo.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnEscaneoMouseExited

    private void btnEscaneoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscaneoMousePressed
        btnEscaneo.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnEscaneoMousePressed

    private void btnEscaneoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscaneoMouseReleased

    }//GEN-LAST:event_btnEscaneoMouseReleased

    private void btnEscaneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscaneoActionPerformed
        EscaneoDiccionario p1 = new EscaneoDiccionario();
        CambioPanel(p1);
    }//GEN-LAST:event_btnEscaneoActionPerformed

    private void btnDiccionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiccionarioMouseClicked
        btnDiccionario.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnDiccionarioMouseClicked

    private void btnDiccionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiccionarioMouseEntered
        btnDiccionario.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnDiccionarioMouseEntered

    private void btnDiccionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiccionarioMouseExited
        btnDiccionario.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnDiccionarioMouseExited

    private void btnDiccionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiccionarioMousePressed
        btnDiccionario.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnDiccionarioMousePressed

    private void btnDiccionarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiccionarioMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiccionarioMouseReleased

    private void btnDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiccionarioActionPerformed
        Diccionario d = new Diccionario();
        d.setDefaultCloseOperation(Diccionario.DISPOSE_ON_CLOSE);
        d.setVisible(true);
    }//GEN-LAST:event_btnDiccionarioActionPerformed

    private void btnAFDoAFNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAFDoAFNDMouseClicked
        btnAFDoAFND.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnAFDoAFNDMouseClicked

    private void btnAFDoAFNDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAFDoAFNDMouseEntered
        btnAFDoAFND.setBackground(new Color(171, 197, 215));
    }//GEN-LAST:event_btnAFDoAFNDMouseEntered

    private void btnAFDoAFNDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAFDoAFNDMouseExited
        btnAFDoAFND.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnAFDoAFNDMouseExited

    private void btnAFDoAFNDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAFDoAFNDMousePressed
        btnAFDoAFND.setBackground(new Color(98, 150, 185));
    }//GEN-LAST:event_btnAFDoAFNDMousePressed

    private void btnAFDoAFNDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAFDoAFNDMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAFDoAFNDMouseReleased

    private void btnAFDoAFNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAFDoAFNDActionPerformed
        Tabla_AFD_AFND p2 = new Tabla_AFD_AFND();
        CambioPanel(p2);
    }//GEN-LAST:event_btnAFDoAFNDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel barraOpciones;
    private javax.swing.JButton btnAFDoAFND;
    private javax.swing.JButton btnAnalizador;
    private javax.swing.JButton btnDiccionario;
    private javax.swing.JButton btnEscaneo;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
